### ISSUE TITLE
Issue (IPAD PRO and IPAD AIR)-Message-All fonts should be increase check the screen

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#250]
All   fonts should be increase check the screen

**Comment by vijaydemonz** [comment]
Resolved

**Comment by LalithaCharla** [comment]
Resolved but the font and sizes are displaying little difference as i am Testing in IPAD pro(12.9) simulator

**Comment by LalithaCharla** [comment]
Fixed
