### ISSUE TITLE
equipment - clouds - Sunny -Font style, size,Knob dimensions

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#267]
1. Font style, size and text block size (wrapping should match design)
2. Knob dimensions - looks narrow than design
THE SNAP FEATURE HAS A BUG HERE. IT SHOULD SNAP TO NEAREST POINT WHEN DRAGGED AND LEFT 25% CLOSE TO THE POINT
3. Images - dimensions ratio should match design
4. Font style, size
5. Font style, size
6. Font style, size
7, 8. Button size, font style
9. Spacing between buttons

![IMG_0047](https://user-images.githubusercontent.com/35054743/74908353-ab978a80-53db-11ea-8567-7b054419640b.jpg)

**Comment by TheMetroGuy** [comment]
Slider Knob image is wrong

**Comment by TheMetroGuy** [comment]
THE SNAP FEATURE HAS A BUG HERE. IT SHOULD SNAP TO NEAREST POINT WHEN DRAGGED AND LEFT 25% CLOSE TO THE POINT

**Comment by LalithaCharla** [comment]
fIxed
