### ISSUE TITLE
Equipment- cloud- partialcloud- Text font style, size and wrapping,Box Background image

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#269]
1. Cross button size and image
2. Text font style, size and wrapping
3. Box Background image
4. Progress bar size should be 110% (or 120%) check the design. Right now it's filled only to 100%
![partial cloud](https://user-images.githubusercontent.com/35054743/74908730-ab4bbf00-53dc-11ea-919e-f6a79ff699c6.jpg)

**Comment by TheMetroGuy** [comment]
1. Box background image is wrong
2. Close icon size is too small compared to XD

**Comment by TheMetroGuy** [comment]
The info box issues are still open, the background image and the close button spacing and size.
