### ISSUE TITLE
Finance option screen

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#271]
1. Header font style and size
2. Footer buttons states (green and red icons) on top of icons should match state
3. Footer sliding when tapped on Survey

![F6AC3CA9-3874-4B1F-B7A7-B0BFFA7E0DCD](https://user-images.githubusercontent.com/35054743/74909832-244c1600-53df-11ea-93c7-982be9e07c51.jpeg)

**Comment by ijazakram** [comment]
@LalithaCharla I think,  this issue was fixed @ latest binary. 
please cross check this bug in the latest binary. And share your comments.

**Comment by ijazakram** [comment]
Vijay you never CLOSE bugs. Only @LalithaCharla / Chaitanya / ME will close issue.
Please consider this.

**Comment by vijaydemonz** [comment]
ok sir
