### ISSUE TITLE
Camera button not working until 'photos' button is tapped

### ISSUE THREAD

**Issue by TheMetroGuy** [LalithaCharla/Kanobe-Phase3#273]
The camera button is not doing anything until the photos button is tapped. The camera button starts working after that but won't respond if you tap that first. Close the app, re-open and then try.

Happens for all the screens in the signing section

![IMG_0059](https://user-images.githubusercontent.com/1797971/75126962-5339e480-568a-11ea-8821-1df61780421f.PNG)

**Comment by VasuPronteff** [comment]
Resolved
