### ISSUE TITLE
Font sizes, colors, missing phone number

### ISSUE THREAD

**Issue by TheMetroGuy** [LalithaCharla/Kanobe-Phase3#274]
See attached

![IMG_0060](https://user-images.githubusercontent.com/1797971/75127089-21754d80-568b-11ea-808d-a12abade9229.PNG)

**Comment by ijazakram** [comment]
PHONE NUMBER::- 
Phone number is not missed. When we are not receiving from the API service then its EMPTY. But you can EDIT & ENTER the Phone number. Please cross check from your end.

**Comment by LalithaCharla** [comment]
Fixed

**Comment by VasuPronteff** [comment]
Styles added.

**Comment by LalithaCharla** [comment]
Resolved
