### ISSUE TITLE
YESSSS button not activated when all the four are turned green

### ISSUE THREAD

**Issue by TheMetroGuy** [LalithaCharla/Kanobe-Phase3#276]
YESSSS button should turn green

![IMG_0060 copy](https://user-images.githubusercontent.com/1797971/75127629-2b4c8000-568e-11ea-821f-264b57876b18.PNG)

**Comment by VasuPronteff** [comment]
Condition added.

**Comment by VasuPronteff** [comment]
Condition added.

**Comment by LalithaCharla** [comment]
Fixed
