### ISSUE TITLE
Finance option -signin pages

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#283]
1)Send - name should change to attach 
2) Down menu icons alignments
3)header alignments(Name, address,phonenumbers)
4)survey button is enabled only when the 4 icons( finance docs, install docs, usage docs and design) are clicked 
5)The space between the header and loan pal (approval)
6)Calendar- From the selected day only the calender should be enabled to select and the before the selected day it should be disable 
7) Yes or no- for the first question if we click on yes then only it should ask the next question then if we select the second question then only the check mark should be displayed (propertygates,pets,homewonersasscociation,exisitng structure)
8)Yes - down menu the yess button size should be increased
9)After cliking the yes then the new page yes should be displayed if we click on yes then in the proposals page the signin should change to green .

**Comment by VasuPronteff** [comment]
2) Down menu icons alignments - pending
Others resolved

**Comment by LalithaCharla** [comment]
2)Down menu icons alignments - pending
9)After cliking the yes then the new page yes should be displayed if we click on yes then in the proposals page the signin should change to green .- pending
