### ISSUE TITLE
Info-Keyboard glitches and you can move from multiple ﬁelds with it still staying up

### ISSUE THREAD

**Issue by LalithaCharla** [LalithaCharla/Kanobe-Phase3#45]
Keyboard glitches and you can move from multiple ﬁelds with it still staying up-
Please   keep the pre ﬁlled text you have there for now though. Just have it save it   if you change it or click the check mark.
--

**Comment by vijaydemonz** [comment]
resolved

**Comment by LalithaCharla** [comment]
Fixed
